### ISSUE TITLE
Not issue, just question

### ISSUE THREAD

**Issue by eouia** [ejay-ibm/MMM-SpotifyControl#1]
I need some concept understanding of this module.

- Does this module need Raspotify to play songs?
- It seems Only controlling current Spotify playing(with Raspotify) is the object of this module, right?
- I think it's a kind of SpotifyConnect, so it should be activated from other Spotify Host - like spotify app of phone. right?
- Is it possible to play music(tracklist) of specific user on start or runtime without any other Spotify Host(phone app)?

**Comment by Ejay-3D** [comment]
1- Does this module need Raspotify to play songs? 
Not at all, you could play song on any devices  

2- It seems Only controlling current Spotify playing(with Raspotify) is the object of this module, right?
the default device name is configured in the config.js. ( I'm working on retrieving the device ID from the name at this time ), but since i'm not a good dev I think i'm struggling with the way to make it . 

else if the device name is not define , you will need to have an active device ( device where spotify is already open) to start playing song on it. Else you will fial with the issue i'm trying to resolve now : 
  message: 'Player command failed: No active device found',
        reason: 'NO_ACTIVE_DEVICE' } },

this is why I need to at least get a default device id or convert name from config.js to ID 
So having raspotify or not is not important . raspotify is just a device like antoher. 


3-I think it's a kind of SpotifyConnect, so it should be activated from other Spotify Host - like spotify app of phone. right? I'm working on a way to activate device automatically with a voice command . but that will be in a next step . 

4-Is it possible to play music(tracklist) of specific user on start or runtime without any other Spotify Host(phone app)?
I think yes . Everything this is here : https://developer.spotify.com/console/
is usable . 

Ejay

**Comment by eouia** [comment]
More..
> Not at all, you could play song on any devices

Maybe the devices mean Spotify enabled smart speaker or my ipad or TV,... right?
But If I want to play Spotify on MM directly?

**Comment by Ejay-3D** [comment]
But If I want to play Spotify on MM directly? 
You need to specify a deviceId in the config.js 
So the player will run on that specific device. 

To get your device list enable them by playing a song on them . 
and then go to 
https://developer.spotify.com/console/get-users-available-devices/

Device must be active to be view here first.

**Comment by eouia** [comment]
But how can you play Spotify on MM? MM might be not an instance of SpotifyConnect. When you enable Raspotify on RPI, at that time it could be a SpotifyConnect which has deviceID.
In that case, MM would be a "Streaming Speaker" from your Spotify App.

I'm thinking of standalone Spotify Player, without Raspotify, without any Smart phone app. So I asked for my understanding.

**Comment by Ejay-3D** [comment]
But how can you play Spotify on MM?  
Yes you need raspotify definitely to play your music on the mirror. 
Your understanding is correct. 

This module just send simple REST call to control the streaming on the select device.

**Comment by Ejay-3D** [comment]
Closing for now, please reopen if you have any additional questions.
